- type: job
  id: OS14SecurityMarshall
  name: job-name-OS14SecurityMarshall
  description: job-description-OS14SecurityMarshall
  playTimeTracker: OS14SecurityMarshall
  requirements:
    - !type:SpeciesRequirement # CorvaxGoob-Species
      inverted: true
      species:
      - Abductor
  guides:
  - Command
  weight: 20
  startingGear: OS14SecurityMarshallGear
  icon: "JobIconCaptain"
  joinNotifyCrew: false
  supervisors: job-supervisors-nobody
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: Condemned
        soulOwnedNotDevil: true

- type: startingGear
  id: OS14SecurityMarshallGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryColorDarkBlue
    head: ClothingHeadHatBeretCommand
    shoes: ClothingShoesSwat
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    id: CaptainPDA
    back: ClothingBackpackSatchelLeather
    belt: Stunbaton
  storage:
    back:
    - WeaponTaser
