// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Aquila.PDA; // Aquila Change
using Content.Shared._DV.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatEntry : BoxContainer
{
    public event Action<uint>? OnPressed;
    private uint _number;
    private Action<EventArgs>? _pressHandler;

    public NanoChatEntry()
    {
        RobustXamlLoader.Load(this);
        // Aquila Change start
        UnreadIndicator.PanelOverride = PdaStyle.Box(PdaStyle.Red);
        NameLabel.FontColorOverride = PdaStyle.TextHeader;
        AvatarLabel.FontColorOverride = Color.White;
        // Aquila Change end
    }

    public void SetRecipient(NanoChatRecipient recipient, uint number, bool isSelected)
    {
        // Remove old handler if it exists
        if (_pressHandler != null)
            ChatButton.OnPressed -= _pressHandler;

        _number = number;

        // Create and store new handler
        _pressHandler = _ => OnPressed?.Invoke(_number);
        ChatButton.OnPressed += _pressHandler;

        NameLabel.Text = recipient.Name;
        JobLabel.Text = recipient.JobTitle ?? "";
        JobLabel.Visible = !string.IsNullOrEmpty(recipient.JobTitle);
        UnreadIndicator.Visible = recipient.HasUnread;

        // Aquila Change start
        Avatar.PanelOverride = PdaStyle.Box(PdaStyle.AvatarColors[number % PdaStyle.AvatarColors.Length]);
        AvatarLabel.Text = string.IsNullOrWhiteSpace(recipient.Name)
            ? "?"
            : char.ToUpperInvariant(recipient.Name.TrimStart()[0]).ToString();

        ChatButton.ModulateSelfOverride = isSelected ? PdaStyle.Selected : null;
        // Aquila Change end
    }
}
