// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Aquila.Emoji; // Aquila Change
using Content.Client._Aquila.PDA; // Aquila Change
using Content.Shared._DV.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility; // Goob

namespace Content.Client._DV.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMessageBubble : BoxContainer
{
    public static readonly Color OwnMessageColor = PdaStyle.AccentDark; // Aquila Change
    public static readonly Color OtherMessageColor = PdaStyle.Selected; // Aquila Change
    public static readonly Color BorderColor = PdaStyle.BackgroundTertiary.WithAlpha(0.4f); // Aquila Change
    public static readonly Color TextColor = Color.White; // Aquila Change
    public static readonly Color ErrorColor = PdaStyle.Red; // Aquila Change

    public NanoChatMessageBubble()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetMessage(NanoChatMessage message, bool isOwnMessage)
    {
        // Aquila Change start
        var style = PdaStyle.Box(isOwnMessage ? OwnMessageColor : OtherMessageColor);
        style.SetContentMarginOverride(StyleBox.Margin.Horizontal, 10);
        style.SetContentMarginOverride(StyleBox.Margin.Vertical, 6);
        MessagePanel.PanelOverride = style;

        MessageText.SetMessage(EmojiList.Parse(message.Content), [typeof(EmojiTag)], TextColor);

        TimeLabel.HorizontalAlignment = isOwnMessage ? HAlignment.Right : HAlignment.Left;
        TimeLabel.FontColorOverride = PdaStyle.TextMuted;
        // Aquila Change end

        // Show delivery failed text if needed (only for own messages)
        DeliveryFailedLabel.Visible = isOwnMessage && message.DeliveryFailed;
        if (DeliveryFailedLabel.Visible)
            DeliveryFailedLabel.Modulate = ErrorColor;

        // For own messages: FlexSpace -> MessagePanel -> RightSpacer
        // For other messages: LeftSpacer -> MessagePanel -> FlexSpace
        MessageContainer.RemoveAllChildren();

        // fuuuuuck
        MessageBox.Parent?.RemoveChild(MessageBox);

        if (isOwnMessage)
        {
            MessageContainer.AddChild(FlexSpace);
            MessageContainer.AddChild(MessageBox);
            MessageContainer.AddChild(RightSpacer);
        }
        else
        {
            MessageContainer.AddChild(LeftSpacer);
            MessageContainer.AddChild(MessageBox);
            MessageContainer.AddChild(FlexSpace);
        }
    }

    // Aquila Change start
    public void SetTime(string? time)
    {
        TimeLabel.Text = time ?? string.Empty;
        TimeLabel.Visible = time != null;
    }
    // Aquila Change end
}
