- type: aqSetting
  id:  SS14
  weight: 10
  name: aq-setting-ss14

- type: aqSetting
  id:  OS14
  weight: 9
  name: aq-setting-os14

- type: aqSetting
  id:  Elysium
  weight: 8
  name: aq-setting-elysium
