// SPDX-License-Identifier: MIT

using Content.Client._Aquila.PDA; // Aquila Change
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaNavigationButton : ContainerButton
{

    private bool _isCurrent;
    private bool _isActive = true;

    // Aquila Change start
    private Thickness _borderThickness = new(0, 0, 0, 1);
    private Thickness _currentTabBorderThickness = new(0, 0, 0, 2);

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = PdaStyle.BackgroundSecondary,
        BorderColor = PdaStyle.BackgroundTertiary,
        BorderThickness = new Thickness(0, 0, 0, 1)
    };

    public string InactiveBgColor { get; set; } = PdaStyle.BackgroundSecondaryHex;
    public string ActiveBgColor { get; set; } = PdaStyle.BackgroundHex;
    public string HoverBgColor { get; set; } = PdaStyle.HoverHex;
    public string InactiveFgColor { get; set; } = PdaStyle.TextDisabledHex;
    public string ActiveFgColor { get; set; } = PdaStyle.TextHeaderHex;
    public string IdleLabelColor { get; set; } = PdaStyle.TextInteractiveHex;
    public string HoverLabelColor { get; set; } = PdaStyle.TextNormalHex;
    public string BorderColor { get; set; } = PdaStyle.BackgroundTertiaryHex;
    public string CurrentBorderColor { get; set; } = PdaStyle.AccentHex;
    private bool _loaded;
    // Aquila Change end

    public SpriteSpecifier? IconTexture
    {
        set
        {
            Icon.Visible = value != null;
            Label.Visible = value == null;

            if (value is not null)
                Icon.SetFromSpriteSpecifier(value);
        }
    }

    public Vector2 IconScale
    {
        get => Icon.DisplayRect.TextureScale;
        set => Icon.DisplayRect.TextureScale = value;
    }

    public string? LabelText
    {
        get => Label.Text;
        set => Label.Text = value;
    }

    /// <summary>
    /// Sets the border thickness when the tab is not the currently active one
    /// </summary>
    public Thickness BorderThickness
    {
        get => _borderThickness;
        set
        {
            _borderThickness = value;
            UpdateStyle(); // Aquila Change
        }
    }

    /// <summary>
    /// Sets the border thickness when this tab is the currently active tab
    /// </summary>
    public Thickness CurrentTabBorderThickness
    {
        get => _currentTabBorderThickness;
        set
        {
            _currentTabBorderThickness = value;
            UpdateStyle(); // Aquila Change
        }
    }

    public bool IsCurrent
    {
        get => _isCurrent;
        set
        {
            _isCurrent = value;
            UpdateStyle(); // Aquila Change
        }
    }

    public bool IsActive
    {
        get => _isActive;
        set
        {
            _isActive = value;
            UpdateStyle(); // Aquila Change
        }
    }

    public PdaNavigationButton()
    {
        RobustXamlLoader.Load(this);
        Background.PanelOverride = _styleBox;
        _loaded = true; // Aquila Change
        UpdateStyle(); // Aquila Change
    }

    // Aquila Change start
    protected override void EnteredTree()
    {
        base.EnteredTree();
        UpdateStyle();
    }

    protected override void DrawModeChanged()
    {
        base.DrawModeChanged();
        UpdateStyle();
    }

    private void UpdateStyle()
    {
        if (!_loaded)
            return;

        var hovered = !_isCurrent && DrawMode == DrawModeEnum.Hover;

        _styleBox.BackgroundColor = Color.FromHex(_isCurrent ? ActiveBgColor : hovered ? HoverBgColor : InactiveBgColor);
        _styleBox.BorderColor = Color.FromHex(_isCurrent ? CurrentBorderColor : BorderColor);
        _styleBox.BorderThickness = _isCurrent ? _currentTabBorderThickness : _borderThickness;

        Icon.Modulate = Color.FromHex(_isActive ? ActiveFgColor : InactiveFgColor);

        var labelColor = !_isActive ? InactiveFgColor
            : _isCurrent ? ActiveFgColor
            : hovered ? HoverLabelColor
            : IdleLabelColor;
        Label.FontColorOverride = Color.FromHex(labelColor);
    }
    // Aquila Change end
}