// SPDX-License-Identifier: MIT

using Content.Client._Aquila.PDA; // Aquila Change
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaProgramItem : ContainerButton
{
    public const string StylePropertyBgColor = "backgroundColor";
    public const string NormalBgColor = PdaStyle.BackgroundSecondaryHex; // Aquila Change
    public const string HoverColor = PdaStyle.HoverHex; // Aquila Change

    // Aquila Change start
    private readonly StyleBoxFlat _styleBox = PdaStyle.Box(PdaStyle.BackgroundSecondary);

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor;
        set => _styleBox.BackgroundColor = value;
    }

    public PdaProgramItem()
    {
        RobustXamlLoader.Load(this);
        Panel.PanelOverride = _styleBox;
        IconBackground.PanelOverride = PdaStyle.Box(PdaStyle.Selected);
        ProgramName.FontColorOverride = PdaStyle.TextHeader;
    }
    // Aquila Change end

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            BackgroundColor = bgColor;

    }
}
