// SPDX-License-Identifier: MIT

using Content.Client._Aquila.PDA; // Aquila Change
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaSettingsButton : ContainerButton
{
    public const string StylePropertyFgColor = "foregroundColor";
    public const string StylePropertyBgColor = "backgroundColor";
    public const string NormalBgColor = PdaStyle.TransparentHex; // Aquila Change
    public const string HoverColor = PdaStyle.HoverHex; // Aquila Change
    public const string PressedColor = PdaStyle.SelectedHex; // Aquila Change
    public const string DisabledFgColor = PdaStyle.TextDisabledHex; // Aquila Change
    public const string EnabledFgColor = PdaStyle.TextHeaderHex; // Aquila Change

    private readonly StyleBoxFlat _styleBox = PdaStyle.Box(Color.Transparent); // Aquila Change

    public string? Text
    {
        get => OptionName.Text;
        set => OptionName.Text = value;
    }
    public string? Description
    {
        get => OptionDescription.Text;
        set => OptionDescription.Text = value;
    }

    public Color BackgroundColor
    {
        get => _styleBox.BackgroundColor; // Aquila Change
        set => _styleBox.BackgroundColor = value; // Aquila Change
    }

    public Color? ForegroundColor
    {
        get => OptionName.FontColorOverride;

        set
        {
            OptionName.FontColorOverride = value;
            OptionDescription.FontColorOverride = value == Color.FromHex(EnabledFgColor) ? PdaStyle.TextMuted : value; // Aquila Change
        }
    }

    public PdaSettingsButton()
    {
        RobustXamlLoader.Load(this);
        Panel.PanelOverride = _styleBox;
        Separator.PanelOverride = new StyleBoxFlat { BackgroundColor = PdaStyle.Separator }; // Aquila Change
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (TryGetStyleProperty<Color>(StylePropertyBgColor, out var bgColor))
            BackgroundColor = bgColor;

        if (TryGetStyleProperty<Color>(StylePropertyFgColor, out var fgColor))
            ForegroundColor = fgColor;

    }
}