// Работа выполнена Claude (Anthropic).
// SPDX-FileCopyrightText: 2026 GromPlay739
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Aquila.EventContent.Atlas739;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Aquila.EventContent.Atlas739;

[GenerateTypedNameReferences]
public sealed partial class SotHourglassWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    public event Action? OnVote;

    private SotHourglassBuiState? _state;
    private int _shownSeconds = -1;

    public SotHourglassWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        VoteButton.OnPressed += _ => OnVote?.Invoke();
    }

    public void UpdateState(SotHourglassBuiState state)
    {
        _state = state;
        _shownSeconds = -1;
        Refresh();
    }

    private bool LocalPlayerVoted(SotHourglassBuiState state)
    {
        if (_player.LocalEntity is not { } local)
            return false;

        return state.Voters.Contains(_entMan.GetNetEntity(local));
    }

    private void Refresh()
    {
        if (_state is not { } state)
            return;

        var sideKey = state.Side == SotSide.Athena ? "sot-side-athena" : "sot-side-reapers";
        ShipLabel.Text = Loc.GetString("sot-hourglass-ship", ("side", Loc.GetString(sideKey)), ("id", state.ShipId));

        // За что голосуют в этой фазе: за готовность или за отмену.
        var isReadyVote = state.Phase == SotHourglassPhase.Idle;
        var isCancelVote = state.Phase is SotHourglassPhase.Countdown or SotHourglassPhase.Waiting;
        var canVote = isReadyVote || isCancelVote;

        VotesBar.Visible = canVote;
        VotesLabel.Visible = canVote;
        VoteButton.Visible = canVote;

        if (canVote)
        {
            VotesBar.Value = state.Required <= 0 ? 0f : Math.Clamp(state.Votes / (float) state.Required, 0f, 1f);
            VotesLabel.Text = Loc.GetString(
                isReadyVote ? "sot-hourglass-votes-ready" : "sot-hourglass-votes-cancel",
                ("votes", state.Votes),
                ("required", state.Required));

            var voted = LocalPlayerVoted(state);
            var buttonKey = (isReadyVote, voted) switch
            {
                (true, false) => "sot-hourglass-button-ready",
                (true, true) => "sot-hourglass-button-ready-revoke",
                (false, false) => "sot-hourglass-button-cancel",
                (false, true) => "sot-hourglass-button-cancel-revoke"
            };
            VoteButton.Text = Loc.GetString(buttonKey);
        }

        PhaseLabel.Text = GetPhaseText(state);
        InfoLabel.SetMessage(FormattedMessage.FromUnformatted(
            Loc.GetString($"sot-hourglass-info-{state.Phase}", ("seconds", state.DepartSeconds))));
    }

    private string GetPhaseText(SotHourglassBuiState state)
    {
        var seconds = RemainingSeconds(state);
        return Loc.GetString($"sot-hourglass-phase-{state.Phase}", ("seconds", seconds));
    }

    private int RemainingSeconds(SotHourglassBuiState state)
    {
        if (state.DepartAt is not { } at)
            return 0;

        return Math.Max(0, (int) Math.Ceiling((at - _timing.CurTime).TotalSeconds));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Обратный отсчёт обновляется на клиенте сам, сервер шлёт только время вылета.
        if (_state is not { Phase: SotHourglassPhase.Countdown } state)
            return;

        var seconds = RemainingSeconds(state);
        if (seconds == _shownSeconds)
            return;

        _shownSeconds = seconds;
        PhaseLabel.Text = GetPhaseText(state);
    }
}
