using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Aquila.OocNotes;

[GenerateTypedNameReferences]
public sealed partial class OocNotesEditor : Control
{
    public event Action<string>? OnNotesChanged;

    public OocNotesEditor()
    {
        RobustXamlLoader.Load(this);

        HintLabel.Text = Loc.GetString("ooc-notes-editor-hint");
        NotesInput.Placeholder = new Rope.Leaf(Loc.GetString("ooc-notes-editor-placeholder"));
        NotesInput.OnTextChanged += _ => OnNotesChanged?.Invoke(Rope.Collapse(NotesInput.TextRope).Trim());
    }

    public void SetNotes(string notes)
    {
        NotesInput.TextRope = new Rope.Leaf(notes);
    }
}
